version: '3'

services:
    app:
        container_name: ${DOCKER_APP_NAME}
        restart: unless-stopped
        build:
            context: .docker/build/app
            dockerfile: Dockerfile
        image: ${DOCKER_APP_NAME}-apache2-mod_php-${PHP_VERSION}
        environment:
            CONTAINER_ROLE: app
        volumes:
            - .docker/apache2/:/etc/apache2
            - ${CODEBASE_PATH}:/var/www/html
        networks:
            - app-network
        ports:
            - "${DOCKER_WEBSERVER_HTTP_PORT}:80"
            - "${DOCKER_WEBSERVER_HTTPS_PORT}:443"
        depends_on:
            - db
            - memcached

    scheduler:
        container_name: ${DOCKER_APP_NAME}-scheduler
        restart: unless-stopped
        image: ${DOCKER_APP_NAME}-apache2-mod_php-${PHP_VERSION}
        environment:
            CONTAINER_ROLE: scheduler
        volumes:
            - .docker/apache2/:/etc/apache2
            - ${CODEBASE_PATH}:/var/www/html
        networks:
            - app-network
        depends_on:
            - app

    queue:
        container_name: ${DOCKER_APP_NAME}-queue
        restart: unless-stopped
        image: ${DOCKER_APP_NAME}-apache2-mod_php-${PHP_VERSION}
        environment:
            CONTAINER_ROLE: queue
            APP_ENV: ${APP_ENV:-local}
            QUEUE: default
        volumes:
            - .docker/apache2/:/etc/apache2
            - ${CODEBASE_PATH}:/var/www/html
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mariadb
        container_name: ${DOCKER_DB_NAME}
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/mysql
        command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-flush-log-at-trx-commit=0

    memcached:
        image: memcached:alpine
        container_name: ${DOCKER_CACHE_NAME}
        restart: unless-stopped
        ports:
            - 11211:11211
        networks:
            - app-network

    adminer:
        image: adminer
        container_name: ${DOCKER_DB_NAME}-adminer
        restart: unless-stopped
        environment:
            ADMINER_DESIGN: haeckel
        networks:
            - app-network
        ports:
            - ${ADMINER_PORT}:8080
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
